; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "NexGuard  Scanner"
#define MyAppVersion "1.0"
#define MyAppPublisher "AZAS DEVELOPER"
#define MyAppExeName "ProyectoAntivirus.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4657ABFF-2B6A-4334-B28C-BBF51A747BA0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputDir=C:\Users\Bohr\Desktop\IMPETU\NexGuard  Scanner
OutputBaseFilename=setup
SetupIconFile=C:\Users\Bohr\Documents\Proyectos Code\ProyectoAntivirus\ProyectoAntivirus\assets\insecto.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Bohr\Documents\Proyectos Code\ProyectoAntivirus\ProyectoAntivirus\dist\ProyectoAntivirus.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Bohr\Documents\Proyectos Code\ProyectoAntivirus\ProyectoAntivirus\build\ProyectoAntivirus\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

